openapi: "3.0.0"
info:
  version: 1.0.0
  title: Workflow tool
  description: PFN 2019 Internship Challenge
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:8080/api

paths:
  /jobs:
    get:
      parameters:
        - name: created
          in: query
          description: job created time
          required: false
          style: form
          schema:
            type: string
      responses:
        '200':
          description: jobs response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Job'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Job:
      required:
        - id
        - created
        - priority
        - tasks
      properties:
        id:
          type: integer
          format: int32
          description: id of the job
          example: 1
        created:
          type: string
          description: created time of the job
          example: 00:00:01
        priority:
          type: string
          description: priority of the job
          example: Low
        tasks:
          type: array
          items:
            type: integer
            format: int32
          example: [5,6,7]
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
          description: Error code
        message:
          type: string
          description: Error message
