/*
 * dagdig
 *
 * PFN 2019 Internship Challenge
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Job struct {

	// id of the job
	Id int32 `json:"id"`

	// created time of the job
	Created string `json:"created"`

	// priority of the job
	Priority string `json:"priority"`

	Tasks []int32 `json:"tasks"`
}
